# Generated by Django 5.0.1 on 2024-05-01 13:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('img', models.FileField(blank=True, null=True, upload_to='img/service/')),
            ],
        ),
        migrations.CreateModel(
            name='SingleService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('plan_vip', models.CharField(blank=True, max_length=512, null=True)),
                ('plan_standart', models.CharField(blank=True, max_length=512, null=True)),
                ('img', models.FileField(blank=True, null=True, upload_to='img/singleservice/')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
