# Generated by Django 5.0.1 on 2024-05-05 15:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_rename_tour_singleservice_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ru', models.CharField(blank=True, max_length=256, null=True)),
                ('description_uz', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='singleservice',
            old_name='descriptio_ru',
            new_name='description_ru',
        ),
        migrations.RemoveField(
            model_name='singleservice',
            name='plan_standar_ru',
        ),
        migrations.RemoveField(
            model_name='singleservice',
            name='plan_standart_en',
        ),
        migrations.RemoveField(
            model_name='singleservice',
            name='plan_standart_uz',
        ),
        migrations.RemoveField(
            model_name='singleservice',
            name='plan_vip_en',
        ),
        migrations.RemoveField(
            model_name='singleservice',
            name='plan_vip_ru',
        ),
        migrations.RemoveField(
            model_name='singleservice',
            name='plan_vip_uz',
        ),
        migrations.AddField(
            model_name='singleservice',
            name='name_ru',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='PlanStandart',
            fields=[
                ('plan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='service.plan')),
            ],
            options={
                'abstract': False,
            },
            bases=('service.plan',),
        ),
        migrations.CreateModel(
            name='PlanVip',
            fields=[
                ('plan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='service.plan')),
            ],
            options={
                'abstract': False,
            },
            bases=('service.plan',),
        ),
        migrations.AddField(
            model_name='plan',
            name='single',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.singleservice'),
        ),
    ]
