# Generated by Django 5.0.1 on 2024-05-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='name_en',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='name_uz',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='singleservice',
            name='name_en',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='singleservice',
            name='name_uz',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
