# Generated by Django 5.0.1 on 2024-05-18 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_plan_name_en_plan_name_uz_singleservice_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='singleservice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='singleservice',
            name='updated_at',
        ),
    ]
