# Generated by Django 5.0.1 on 2024-06-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('language', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Uz'), (2, 'Ru')], default=0)),
                ('additional_data', models.CharField(blank=True, max_length=511, null=True)),
            ],
        ),
    ]
