# Generated by Django 5.0.1 on 2024-06-10 11:51

import apps.pdf.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_ru', models.CharField(blank=True, max_length=256, null=True)),
                ('date', models.FileField(blank=True, null=True, upload_to='pdf/', validators=[apps.pdf.models.validate_file_size])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RusData',
            fields=[
                ('data_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pdf.data')),
            ],
            options={
                'abstract': False,
            },
            bases=('pdf.data',),
        ),
        migrations.CreateModel(
            name='UzbData',
            fields=[
                ('data_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pdf.data')),
            ],
            options={
                'abstract': False,
            },
            bases=('pdf.data',),
        ),
    ]
