# Generated by Django 5.0.1 on 2024-05-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_certificates_mentors_univerlogo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificates',
            old_name='name',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='mentors',
            old_name='name',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='mentors',
            old_name='work',
            new_name='name_ru',
        ),
        migrations.RenameField(
            model_name='univerlogo',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='certificates',
            name='name_ru',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='certificates',
            name='name_uz',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='mentors',
            name='name_uz',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='mentors',
            name='work_en',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='mentors',
            name='work_ru',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='mentors',
            name='work_uz',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='univerlogo',
            name='name_ru',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='univerlogo',
            name='name_uz',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
