# Generated by Django 5.0.1 on 2024-05-05 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_name_certificates_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificates',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='certificates',
            name='name_uz',
        ),
    ]
