# Generated by Django 5.0.1 on 2024-05-17 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_certificates_name_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiLingualText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ru', models.CharField(blank=True, max_length=1024, null=True)),
                ('en', models.CharField(blank=True, max_length=1024, null=True)),
                ('uzb', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_bottom', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title_bottom', to='main.multilingualtext')),
                ('title_sub', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title_sub', to='main.multilingualtext')),
                ('title_top', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title_top', to='main.multilingualtext')),
            ],
        ),
        migrations.CreateModel(
            name='AboutMentors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(blank=True, null=True, upload_to='img/aboutmentors/')),
                ('text4', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text4', to='main.multilingualtext')),
                ('text5', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text5', to='main.multilingualtext')),
                ('text6', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text46', to='main.multilingualtext')),
                ('title', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title', to='main.multilingualtext')),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(blank=True, null=True, upload_to='img/about/')),
                ('text1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text1', to='main.multilingualtext')),
                ('text2', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text2', to='main.multilingualtext')),
                ('text3', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text3', to='main.multilingualtext')),
                ('title1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title1', to='main.multilingualtext')),
                ('title2', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title2', to='main.multilingualtext')),
                ('title3', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title3', to='main.multilingualtext')),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(blank=True, null=True, upload_to='img/stats/')),
                ('title_bottom2', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title_bottom2', to='main.multilingualtext')),
                ('title_top2', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title_top2', to='main.multilingualtext')),
            ],
        ),
        migrations.CreateModel(
            name='WhyUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(blank=True, null=True, upload_to='img/whyUs/')),
                ('title_bottom3', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title_bottom3', to='main.multilingualtext')),
                ('title_top3', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title_top3', to='main.multilingualtext')),
            ],
        ),
    ]
