# Generated by Django 5.0.1 on 2024-05-18 09:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_multilingualtext_hero_aboutmentors_about_stats_whyus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='title_bottom',
        ),
        migrations.RemoveField(
            model_name='about',
            name='text1',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='title_top2',
        ),
        migrations.RemoveField(
            model_name='aboutmentors',
            name='text5',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='title_bottom2',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='title_top',
        ),
        migrations.RemoveField(
            model_name='about',
            name='text2',
        ),
        migrations.RemoveField(
            model_name='aboutmentors',
            name='text6',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title1',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title3',
        ),
        migrations.RemoveField(
            model_name='aboutmentors',
            name='text4',
        ),
        migrations.RemoveField(
            model_name='whyus',
            name='title_bottom3',
        ),
        migrations.RemoveField(
            model_name='aboutmentors',
            name='title',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title2',
        ),
        migrations.RemoveField(
            model_name='about',
            name='text3',
        ),
        migrations.RemoveField(
            model_name='whyus',
            name='title_top3',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='title_sub',
        ),
        migrations.RemoveField(
            model_name='certificates',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='certificates',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='mentors',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mentors',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='univerlogo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='univerlogo',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='about',
            name='text_1_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='text_1_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='text_1_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='text_2_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='text_2_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='text_2_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='text_3_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='text_3_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='text_3_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_1_en',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_1_ru',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_1_uz',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_2_en',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_2_ru',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_2_uz',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_3_en',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_3_ru',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_3_uz',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='aboutmentors',
            name='text_1_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutmentors',
            name='text_1_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutmentors',
            name='text_1_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutmentors',
            name='text_2_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutmentors',
            name='text_2_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutmentors',
            name='text_2_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutmentors',
            name='text_3_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutmentors',
            name='text_3_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutmentors',
            name='text_3_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutmentors',
            name='title_en',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='aboutmentors',
            name='title_ru',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='aboutmentors',
            name='title_uz',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='title_bottom_en',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='title_bottom_ru',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='title_bottom_uz',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='title_sub_en',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='title_sub_uru',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='title_sub_uz',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='title_top_en',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='title_top_ru',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='title_top_uz',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='stats',
            name='title_bottom_en',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='stats',
            name='title_bottom_ru',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='stats',
            name='title_bottom_uz',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='stats',
            name='title_top_en',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='stats',
            name='title_top_ru',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='stats',
            name='title_top_uz',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='whyus',
            name='title_bottom_en',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='whyus',
            name='title_bottom_ru',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='whyus',
            name='title_bottom_uz',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='whyus',
            name='title_top_en',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='whyus',
            name='title_top_ru',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='whyus',
            name='title_top_uz',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='about',
            name='img',
            field=models.FileField(upload_to='img/about/'),
        ),
        migrations.AlterField(
            model_name='aboutmentors',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aboutmentors',
            name='img',
            field=models.FileField(upload_to='img/about_mentors/'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stats',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='whyus',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='MultiLingualText',
        ),
    ]
