# Generated by Django 5.0.1 on 2024-06-12 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_hero_title_bottom_remove_about_text1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='title_sub_uru',
            new_name='title_sub_ru',
        ),
    ]
